name: Build and Deploy
on:
  push:
    branches:
      - release
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with: 
        node-version: 25
    - name: Install Dependencies
      run: npm install

    - name: Deploy to gh pages
      run: |
          npx angular-cli-ghpages --dir=dist/ --no-silent --name="Reece King" --email="reeceking9922@gmail.com"
      env:
        CI: true
        GH_TOKEN: ${{ secrets.MY_PAT }}
